/** 社区成员（演示账号）。
 * 头像 = 昵称首字 + 专属底色；资料仅存于本地，手机号 / 邮箱留空。 */

export const MEMBERS = [
  {
    name: "林知遥",
    nickname: "知遥测不准",
    accountId: "aiquos86645534",
    role: "AI 产品经理",
    expertise: ["能力分级", "测评设计", "团队协作"],
    bio: "负责把模糊的“会用 AI”拆成可测的能力项。相信好的测评先定义场景，再定义分数。",
    joined: "2026-03-12",
    posts: 23,
    likes: 1284,
    color: "#247cf1",
    ink: "#ffffff",
  },
  {
    name: "周屿",
    nickname: "屿见图表",
    accountId: "aiquos10102969",
    role: "数据可视化设计师",
    expertise: ["报告可视化", "雷达图", "信息降噪"],
    bio: "把测评结果画成人能一眼读懂的样子。常说“图例越少，结论越清楚”。",
    joined: "2026-03-18",
    posts: 17,
    likes: 962,
    color: "#00a96d",
    ink: "#ffffff",
  },
  {
    name: "陈序",
    nickname: "陈序优化中",
    accountId: "aiquos20422761",
    role: "后端工程师",
    expertise: ["提示词工程", "自动化流水线", "评测脚本"],
    bio: "用工程方法对待每一次提示词实验：有版本号、有对照组、有验收标准。",
    joined: "2026-03-25",
    posts: 31,
    likes: 1547,
    color: "#7438e5",
    ink: "#ffffff",
  },
  {
    name: "苏一宁",
    nickname: "一宁不苟",
    accountId: "aiquos47948970",
    role: "社区运营",
    expertise: ["活动策划", "内容精选", "新人引导"],
    bio: "AIQUOS 社区的第一批成员。擅长把线下讨论沉淀成能被搜索到的帖子。",
    joined: "2026-03-08",
    posts: 19,
    likes: 873,
    color: "#f568a3",
    ink: "#ffffff",
  },
  {
    name: "何云帆",
    nickname: "云帆跑分中",
    accountId: "aiquos75155382",
    role: "算法研究员",
    expertise: ["评测指标", "失败样例分析", "模型对比"],
    bio: "关注基准之外的边界条件：模型在哪儿失效、失效能否被快速发现和修正。",
    joined: "2026-04-02",
    posts: 27,
    likes: 1310,
    color: "#fb5727",
    ink: "#ffffff",
  },
  {
    name: "顾清和",
    nickname: "清和观察局",
    accountId: "aiquos47655872",
    role: "AI 伦理与合规顾问",
    expertise: ["署名规范", "风险清单", "评测伦理"],
    bio: "研究测评本身的公平性：谁出题、谁打分、分数被谁使用。",
    joined: "2026-04-10",
    posts: 14,
    likes: 788,
    color: "#2b2733",
    ink: "#ffffff",
  },
  {
    name: "徐望舒",
    nickname: "望舒的课堂",
    accountId: "aiquos70912188",
    role: "高校教师 · 教学设计",
    expertise: ["情境命题", "课堂测评", " rubric 评分量规"],
    bio: "把课堂形成性评价的方法带进 AI 测评，坚持“测评是学习的一部分”。",
    joined: "2026-04-22",
    posts: 12,
    likes: 651,
    color: "#ffb703",
    ink: "#17150f",
  },
  {
    name: "黄小满",
    nickname: "小满闯关中",
    accountId: "aiquos91955853",
    role: "在校学生 · 社团骨干",
    expertise: ["校园活动", "新手题库", "闯关赛运营"],
    bio: "办了三届校园 AI 闯关赛。相信十分钟的小任务比一小时的理论课更有说服力。",
    joined: "2026-05-06",
    posts: 21,
    likes: 734,
    color: "#00a96d",
    ink: "#ffffff",
  },
  {
    name: "李声远",
    nickname: "声远脚本屋",
    accountId: "aiquos62743460",
    role: "效率工具作者",
    expertise: ["自动化", "轻量工具链", "批改脚本"],
    bio: "业余写小工具。信条：低判断的动作交给脚本，高判断的决策留给自己。",
    joined: "2026-05-15",
    posts: 16,
    likes: 926,
    color: "#17150f",
    ink: "#ffffff",
  },
  {
    name: "沈观澜",
    nickname: "观澜出题所",
    accountId: "aiquos17426054",
    role: "测评出题人",
    expertise: ["题目结构", "干扰项设计", "难度标定"],
    bio: "职业出题人。一道好题要过五层结构，任何一层偷懒都会被应试技巧钻空子。",
    joined: "2026-05-28",
    posts: 11,
    likes: 604,
    color: "#7438e5",
    ink: "#ffffff",
  },
  {
    name: "闻人夏",
    nickname: "夏日访谈录",
    accountId: "aiquos87582309",
    role: "UX 研究员",
    expertise: ["用户访谈", "报告可读性", "行为证据"],
    bio: "收集分数之外的故事：被测者在哪一步卡住、哪一句话让他们突然开窍。",
    joined: "2026-06-09",
    posts: 9,
    likes: 512,
    color: "#f568a3",
    ink: "#ffffff",
  },
  {
    name: "江野",
    nickname: "野路子开发",
    accountId: "aiquos22449053",
    role: "独立开发者",
    expertise: ["API 接入", "小产品", "成本控制"],
    bio: "一个人维护三款小工具。喜欢把测评能力直接嵌进产品里，而不是另开一个后台。",
    joined: "2026-06-21",
    posts: 13,
    likes: 688,
    color: "#00a96d",
    ink: "#ffffff",
  },
  {
    name: "白鹿原",
    nickname: "白鹿改稿中",
    accountId: "aiquos78936389",
    role: "文案策划",
    expertise: ["报告改写", "人话写作", "案例包装"],
    bio: "负责把“得分 72，维度均衡”翻译成人类语言。认为报告的第一句话决定它会不会被读完。",
    joined: "2026-07-03",
    posts: 10,
    likes: 557,
    color: "#ffb703",
    ink: "#17150f",
  },
  {
    name: "岑晚舟",
    nickname: "晚舟标数据",
    accountId: "aiquos71503173",
    role: "数据标注主管",
    expertise: ["标注质量", "评分一致性", "边界样例"],
    bio: "带过 40 人的标注团队。深知再漂亮的指标，也架不住评分标准各人一套。",
    joined: "2026-07-15",
    posts: 8,
    likes: 473,
    color: "#fb5727",
    ink: "#ffffff",
  },
  {
    name: "温叙",
    nickname: "温叙精选志",
    accountId: "aiquos85452328",
    role: "AI 训练师",
    expertise: ["课程共创", "题库迭代", "每周精选"],
    bio: "每周从社区讨论里挑出值得反复读的五条。整理本身也是一种学习。",
    joined: "2026-07-28",
    posts: 15,
    likes: 819,
    color: "#247cf1",
    ink: "#ffffff",
  },
];

export const MEMBER_MAP = Object.fromEntries(MEMBERS.map((member) => [member.name, member]));
export const NICKNAME_MAP = Object.fromEntries(MEMBERS.map((member) => [member.nickname, member]));

/** 昵称或真名都能定位到成员（论坛界面统一使用昵称）。 */
export function resolveMember(key) {
  return NICKNAME_MAP[key] ?? MEMBER_MAP[key] ?? null;
}

export function memberColor(key) {
  return resolveMember(key)?.color ?? "#cfc7d2";
}

export function memberInk(key) {
  return resolveMember(key)?.ink ?? "#ffffff";
}
